# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6VCUU5rS0QhreP_5Zv-PR7tRaX6_C2c
"""

import os, requests

os.environ["OPENROUTER_API_KEY"] = "sk-or-v1-sk-or-v1-xxx"

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = "meta-llama/llama-3.1-8b-instruct:free"

url = "https://openrouter.ai/api/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}",
    "HTTP-Referer": "https://colab.research.google.com/",
    "X-Title": "test"
}
data = {
    "model": "meta-llama/llama-3.1-8b-instruct:free",
    "messages": [
        {"role": "user", "content": "به فارسی بگو سلام، اتصال برقرار است"}
    ],
    "max_tokens": 50
}

r = requests.post(url, headers=headers, json=data)
print(r.status_code)
print(r.json())

# Naive RAG کم‌حجم و بهینه برای Google Colab
# کمترین دانلود ممکن + فارسی عالی
'''
دانلود مدل embedding: فقط ~90 مگابایت
دیتابیس: ChromaDB → سبک، سریع، بدون دردسر
LLM:
با OpenRouter → دانلود صفر + فارسی عالی
بدون OpenRouter → فقط ~1 GB دانلود یک‌بار (Qwen2-0.5B)
'''
!pip install -q sentence-transformers chromadb pandas openpyxl requests

import pandas as pd
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
from google.colab import files
import io
import requests
import json
from transformers import pipeline

# ============= تنظیمات =============
USE_OPENROUTER = True  # True → بهترین کیفیت و فارسی عالی (دانلود صفر)
                       # False → کاملاً محلی با مدل سبک

# فقط اگر USE_OPENROUTER = True باشه، کلید لازم است (رایگان ثبت‌نام کن در openrouter.ai)
OPENROUTER_API_KEY = "sk-or-v1-sk-or-v1-xxx"  # ← اینجا کلیدت رو بذار (یا خالی بذار و USE_OPENROUTER=False کن)

OPENROUTER_MODEL = "meta-llama/llama-3.1-8b-instruct:free"  # رایگان + فارسی فوق‌العاده

TOP_K = 5  # تعداد نتایج مرتبط (۵ عالیه برای پاسخ کامل)
# ===================================

# مرحله ۱: آپلود فایل FAQ
print("📂 لطفاً فایل FAQ خودتون رو آپلود کنید (CSV یا Excel)")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
print(f"فایل آپلود شد: {file_name}")

# خواندن فایل
if file_name.endswith('.xlsx'):
    df = pd.read_excel(io.BytesIO(uploaded[file_name]))
else:
    df = pd.read_csv(io.BytesIO(uploaded[file_name]))

# تنظیم ستون‌ها (اگر فارسی هستن، اینجا اصلاح کن)
df.columns = ['category', 'question', 'answer']  # ← اگر اسم ستون‌ها فرق داره، تغییر بده
df = df.astype(str).apply(lambda x: x.str.strip())

print(f"✅ {len(df)} سوال و جواب بارگذاری شد.\n")

# مرحله ۲: ساخت اسناد برای جستجو
docs = df.apply(lambda row: f"سوال: {row['question']}\nپاسخ: {row['answer']}\nدسته‌بندی: {row['category']}", axis=1).tolist()

# مرحله ۳: مدل Embedding کم‌حجم و فارسی‌دوست
print("در حال بارگذاری مدل embedding (فقط ~90 مگابایت)...")
embedding_function = SentenceTransformerEmbeddingFunction(model_name="paraphrase-multilingual-MiniLM-L12-v2")

# مرحله ۴: ساخت دیتابیس ChromaDB (سبک‌تر از FAISS)
print("در حال ساخت پایگاه داده وکتوری (ChromaDB)...")
chroma_client = chromadb.Client()  # کاملاً در حافظه
collection = chroma_client.create_collection(
    name="faq_collection",
    embedding_function=embedding_function,
    get_or_create=True
)

# اضافه کردن تمام اسناد
collection.add(
    documents=docs,
    ids=[f"doc_{i}" for i in range(len(docs))]
)

print(f"✅ پایگاه داده با {len(docs)} سند آماده شد.\n")

# مرحله ۵: تابع تولید پاسخ
def generate_answer(query: str, context: str) -> str:
    if USE_OPENROUTER and OPENROUTER_API_KEY != "sk-or-v1-sk-or-v1-xxx":
        # OpenRouter → بهترین کیفیت، فارسی عالی، دانلود صفر
        url = "https://openrouter.ai/api/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "HTTP-Referer": "https://colab.research.google.com/",
            "X-Title": "Naive RAG پروژه دانشجویی"
        }
        data = {
            "model": OPENROUTER_MODEL,
            "messages": [
                {"role": "system", "content": "شما یک دستیار دقیق هستید. فقط بر اساس اطلاعات داده‌شده به فارسی پاسخ دهید. اگر اطلاعات کافی نیست، بگویید 'این موضوع در FAQ موجود نیست'."},
                {"role": "user", "content": f"اطلاعات:\n{context}\n\nسوال: {query}\n\nپاسخ دقیق و کامل:"}
            ],
            "temperature": 0.4,
            "max_tokens": 600
        }
        try:
            response = requests.post(url, headers=headers, json=data, timeout=60)
            if response.status_code == 200:
                return response.json()['choices'][0]['message']['content'].strip()
            else:
                return f"خطا در OpenRouter: {response.status_code}\nمی‌تونید USE_OPENROUTER=False کنید و از مدل محلی استفاده کنید."
        except:
            return "خطا در اتصال به OpenRouter. مدل محلی فعال شد."

    else:
        # مدل محلی سبک (Qwen2 0.5B) — فارسی خیلی بهتر از TinyLlama
        print("(در حال بارگذاری مدل محلی Qwen2-0.5B — فقط یک بار طول می‌کشه)")
        generator = pipeline(
            "text-generation",
            model="Qwen/Qwen2-0.5B-Instruct",
            device=-1  # CPU
        )
        prompt = f"""You are a helpful assistant. Answer in Persian based only on the provided context.

Context:
{context}

Question: {query}

Answer:"""
        result = generator(prompt, max_new_tokens=400, temperature=0.6, do_sample=True)
        return result[0]['generated_text'].split("Answer:")[-1].strip()

# مرحله ۶: حلقه پرسش و پاسخ
print("🤖 سیستم Naive RAG آماده است!\n")
print(f"حالت LLM: {'OpenRouter (Llama 3.1 8B رایگان — فارسی عالی)' if USE_OPENROUTER else 'مدل محلی Qwen2-0.5B (سبک و آفلاین)'}\n")

while True:
    query = input("سوال شما: ").strip()

    if query.lower() in ["exit", "خروج", "quit", "bye"]:
        print("موفق باشی! 👋")
        break

    if not query:
        print("لطفاً سوالی بپرسید.\n")
        continue

    print("\nجستجو در FAQ...")
    results = collection.query(query_texts=[query], n_results=TOP_K)
    context_parts = results['documents'][0]
    context = "\n\n".join(context_parts)

    print("در حال تولید پاسخ...")
    answer = generate_answer(query, context)

    print("\n📌 پاسخ:")
    print(answer)
    print("\n" + "—" * 80 + "\n")

